# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [56]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Create a vector with values ranging from 10 to 49

In [52]:
arr2 = np.arange(10,50)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [6]:
np.shape(arr2)

(40,)

5. Print the type of the previous array in question 3

In [17]:
arr2.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [19]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/r.chagani/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/r.chagani/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/r.chagani/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\w

7. Print the dimension of the array in question 3


In [18]:
arr2.ndim

1

8. Create a boolean array with all the True values

In [30]:
arr3 = np.array([10,20,30,40,50,60,70], dtype = "bool")
arr3

array([ True,  True,  True,  True,  True,  True,  True])

9. Create a two dimensional array




In [3]:
arr4 = np.arange(20).reshape(4,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

10. Create a three dimensional array



In [46]:
arr5 = np.arange(20).reshape(2,2,5)
arr5

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [60]:
np.flip(arr1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [61]:
arr6 = np.zeros(10)
arr6[4] = 1
arr6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [62]:
arr7 = np.identity(3)
arr7

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [64]:
arr8 = np.array([1, 2, 3, 4, 5])
arr9 = arr8.astype("float64")
arr9

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [65]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])

arr3 = arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [66]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
           [7., 2., 12.]])

arr3 = arr2 > arr1
arr3

array([[False,  True, False],
       [ True, False,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [68]:
arr = np.arange(10)
arr[1:10:2]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [70]:
arr = np.arange(10)
arr[1:10:2] = 1
arr

array([0, 1, 2, 1, 4, 1, 6, 1, 8, 1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [72]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [77]:
arr = np.ones(9).reshape(3,3)
arr[1:2,1:2] = 0
arr

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [78]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6], 

            [7, 8, 9]])

arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [80]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,:] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [86]:
arr2d = np.arange(10).reshape(2,5)
arr2d[0,:]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [88]:
arr2d = np.arange(10).reshape(2,5)
arr2d[1,1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [92]:
arr2d = np.arange(10).reshape(2,5)
arr2d[:,2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [101]:
arr1 = np.random.randn(100).reshape(10,10)
a = arr.max()
b = arr.min()
a,b

(2.528631086481534, -3.2230403924091346)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [105]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [3]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

c = np.where(a==b)
c


(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [4]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)

will_data = data[names == "Will"]
will_data



[[ 0.82612751  1.02231386 -1.33198494  1.87424343]
 [ 0.05712118  2.28950444  0.38927999  0.20894006]
 [-0.14377232  1.08891058 -0.25577333 -1.18456072]
 [ 1.24632831  0.22868959 -0.64934152 -0.02651336]
 [-0.66247994  1.2774331   0.56717268 -1.35350137]
 [ 0.02589413  0.01074297 -0.3912165  -0.08653193]
 [-0.7850575   0.8341031  -0.29699029  1.73728048]]


array([[-0.14377232,  1.08891058, -0.25577333, -1.18456072],
       [-0.66247994,  1.2774331 ,  0.56717268, -1.35350137]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

print(data)

filter_data = data[(names != "Will") & (names != "Joe")]
filter_data

[[ 0.18101158 -0.54660103 -1.21354213 -1.24885764]
 [ 0.55583601  0.28283046 -0.94675805 -0.91352727]
 [ 0.55477769 -1.62557606 -0.57534168  1.04132949]
 [-0.29903642 -0.15341432 -0.47823568  0.84780141]
 [-1.68305355  0.44498593 -1.30270657 -0.6192617 ]
 [ 0.03440964  2.25605211 -1.23266975  0.85309404]
 [-1.12302196  1.20248398 -0.18435382 -0.60214572]]


array([[ 0.18101158, -0.54660103, -1.21354213, -1.24885764],
       [-0.29903642, -0.15341432, -0.47823568,  0.84780141]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [7]:
arr = np.arange(1,16).reshape(5,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [8]:
arr = np.arange(1,17).reshape(2,2,4)
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [9]:
arr.swapaxes(1,2)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [16]:
arr = np.arange(10)
np.sqrt(arr)
arr[arr<0.5] = 0
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [18]:
a = np.random.randn(12)
b = np.random.randn(12)
print(a)
print(b)

c = np.maximum(a,b)
print(c)

[-0.96992122 -0.70662025  0.46766506  0.02682732 -2.60386665 -1.31075347
  1.43692885  1.89868443 -1.04274468 -0.69653811  0.21291036 -1.09289466]
[-1.11001604  1.09322445 -0.37239377 -1.40187588  1.86393146  2.02262944
  1.5170889  -0.79864131  0.33869325  2.02455388 -0.0285097   0.43817032]
[-0.96992122  1.09322445  0.46766506  0.02682732  1.86393146  2.02262944
  1.5170889   1.89868443  0.33869325  2.02455388  0.21291036  0.43817032]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names, return_counts = False)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [32]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

c = np.setdiff1d(a,b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [51]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = np.array([[10,10,10]])

print(sampleArray)
print(newColumn)

newArray = np.delete(sampleArray, 1, 1)

np.insert(newArray, 1, newColumn, 1)


[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[10 10 10]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [53]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print(x)
print(y)

c = np.dot(x,y)
c

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [61]:
a = np.random.randn(20)
print(a)

np.cumsum(a)




[ 0.58725649  0.41312572 -0.20122369 -1.84517429  1.06537599  0.11269324
  1.66558893  0.49035119 -1.25872057 -1.5472669   0.29298416 -0.3216716
 -0.69414359 -1.53071837 -2.15773503  0.62858914 -1.77813848 -0.46107256
  1.153499   -1.44980511]


array([ 0.58725649,  1.00038221,  0.79915852, -1.04601576,  0.01936022,
        0.13205346,  1.79764239,  2.28799358,  1.02927301, -0.51799389,
       -0.22500973, -0.54668133, -1.24082492, -2.77154329, -4.92927832,
       -4.30068918, -6.07882766, -6.53990022, -5.38640122, -6.83620633])