# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
arr = np.arange(10).reshape(2,5)
arr


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [5]:
arr1 = np.ones((2,5))
np.vstack((arr,arr1))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:
np.hstack((arr,arr1))

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [11]:
arr.flatten()


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [3]:
arr1 = np.arange(15).reshape(5,3)
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [5]:
arr1.resize((5,3))
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr2 = np.arange(25).reshape(5,5)
arr2**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr3 = np.arange(30).reshape(5,6)
arr3.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
arr3.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [15]:
np.median(arr3)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [18]:
arr3.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [21]:
arr4 = np.arange(16).reshape(4,4)
print(arr4)
trace = np.trace(arr4)
trace

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [22]:
np.linalg.det(arr4)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [26]:
a = np.percentile(arr4,5)
b = np.percentile(arr4,95)

print("5th Percentile is",a)
print("95th Percentile is",b)


5th Percentile is 0.75
95th Percentile is 14.25


## Question:15

### How to find if a given array has any null values?

In [32]:
arr5 = np.array([1,2,3,4,5,6])
np.isnan(arr5).any()

False